apiVersion: v2
name: cert-manager
version: 0.0.0
dependencies:
  - name: cert-manager
    version: v1.15.3
    repository: https://charts.jetstack.io
#  - name: cert-manager-webhook-gandi
#    version: 0.5.1
#    repository: https://sintef.github.io/cert-manager-webhook-gandi