# Copy the root cert into the dex namespace, but rename the key, so it mounts in the container
# as saliman-ca.crt instead of just ca.crt.
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: saliman-root-cert
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: global-secrets
  target:
    name: saliman-root-cert
    creationPolicy: Owner
  data:
    - secretKey: saliman-ca.crt
      remoteRef:
        key: saliman-root-cert
        property: ca.crt
        metadataPolicy: None
