dex:
  # Mount the root certificate if we are our own CA.  We only need the cert file, so use subPath.
  volumeMounts:
    - mountPath: /etc/ssl/certs/saliman-ca.crt
      name: ca-volume
      subPath: saliman-ca.crt
      readOnly: true
  volumes:
    - name: ca-volume
      secret:
        secretName: saliman-root-cert
  config:
    issuer: https://dex.saliman.net
    storage:
      type: kubernetes
      config:
        inCluster: true
    oauth2:
      skipApprovalScreen: true
    connectors:
      - type: oidc
        id: kanidm
        name: Kanidm
        config:
          clientID: $KANIDM_CLIENT_ID
          clientSecret: $KANIDM_CLIENT_SECRET
          redirectURI: https://dex.saliman.net/callback
          issuer: https://auth.saliman.net/oauth2/openid/dex
          # If we are our own CA, we need to specify the rootCA
          rootCA: /etc/ssl/certs/saliman-ca.crt
          # TODO https://github.com/dexidp/dex/pull/3188
          # enablePKCE: true
          scopes:
            - openid
            - profile
            - email
            - groups
    staticClients:
      - id: grafana-sso
        name: Grafana
        redirectURIs:
          - 'https://grafana.saliman.net/login/generic_oauth'
        secretEnv: GRAFANA_SSO_CLIENT_SECRET
      - id: gitea
        name: Gitea
        redirectURIs:
          - 'https://git.saliman.net/user/oauth2/Dex/callback'
        secretEnv: GITEA_CLIENT_SECRET
  envFrom:
    - secretRef:
        name: dex-secrets
  ingress:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: saliman-ca
    hosts:
      - host: &host dex.saliman.net
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - secretName: dex-tls-certificate
        hosts:
          - *host
