# create the root certificate
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: saliman-root-cert
  namespace: cert-manager
spec:
  isCA: true
  secretName: saliman-root-cert
  secretTemplate:
    annotation:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: ""
  duration: 87600h # 10 years
  commonName: saliman-root-cert
  privateKey:
    algorithm: RSA
    size: 2048
  issuerRef:
    name: saliman-root-ca
    kind: Issuer
