#!/bin/sh

echo "WARNING: ArgoCD admin can do anything in the cluster, only use it for just enough initial setup or in emergencies." >&2

# If we already have a kube config, assume the homelab is in it.
if [ -f ~/.kube/config ]; then
    kubectl config use-context homelab
else
    export KUBECONFIG=./metal/kubeconfig.yaml
fi

kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d
echo ""
