#!/bin/sh

# If we already have a kube config, assume the homelab is in it.
if [ -f ~/.kube/config ]; then
    kubectl config use-context homelab
else
    export KUBECONFIG=./metal/kubeconfig.yaml
fi


kubectl get applicationsets --namespace argocd
kubectl get applications --namespace argocd
kubectl get ingress --all-namespaces
