#!/usr/bin/env python

"""
Quick and dirty script for things that I can't/don't have time to do properly yet
TODO: retire this script

This script initializes the users and groups in kanidm, which involves running commands on the pod,
so it can't (I think) be run in a manifest.
"""

import base64
import json
import json
import pexpect
import requests
import subprocess
import sys
import urllib

from rich.console import Console
from kubernetes import client, config
from kubernetes.stream import stream

# https://git.saliman.net/user/settings/applications
# Doing this properly inside the cluster requires:
# - Kubernetes service account
config.load_config()

kanidm_host = client.NetworkingV1Api().read_namespaced_ingress('kanidm', 'kanidm').spec.rules[0].host


# This method gets the root Certificate Authority from the cert-manager.  We'll need this later if
# we want to make https requests from our browsers.  It saves the cert to "root-ca.crt" for use
# later.
def get_root_ca_secret_ca(name: str, namespace: str) -> None:
    # Fetch the secret
    secret = client.CoreV1Api().read_namespaced_secret(name, namespace)
    # Extract and decode the certificate (you can also get tls.key if needed)
    tls_crt_b64 = secret.data.get("ca.crt")
    if not tls_crt_b64:
        raise ValueError("ca.crt not found in secret")

    tls_crt = base64.b64decode(tls_crt_b64)

    # Save to file
    with open("root-ca.crt", "wb") as f:
        f.write(tls_crt)

    print("Certificate saved to root-ca.crt")

# This method gets the Certificate Authority cert from the self-signed TLS cert Kanidm is using.  It
# saves the cert to "kanidm-ca.crt" for use later.
def get_kanidm_tls_secret_ca(name: str, namespace: str) -> None:
    # Fetch the secret
    secret = client.CoreV1Api().read_namespaced_secret(name, namespace)
    # Extract and decode the certificate (you can also get tls.key if needed)
    tls_crt_b64 = secret.data.get("ca.crt")
    if not tls_crt_b64:
        raise ValueError("ca.crt not found in secret")

    tls_crt = base64.b64decode(tls_crt_b64)

    # Save to file
    with open("kanidm-ca.crt", "wb") as f:
        f.write(tls_crt)

    print("Certificate saved to kanidm-ca.crt")


def apply_secret(name: str, namespace: str, data: dict) -> None:
    print(f"Applying {data} to {name}")
    try:
        client.CoreV1Api().read_namespaced_secret(name, namespace)
        patch_body = client.V1Secret(
            metadata=client.V1ObjectMeta(name=name),
            data=data,
        )
        client.CoreV1Api().replace_namespaced_secret(name, namespace, patch_body)
    except client.exceptions.ApiException:
        # Secret doesn't exist, create a new one
        new_secret = client.V1Secret(
            metadata=client.V1ObjectMeta(name=name),
            data=data,
        )
        client.CoreV1Api().create_namespaced_secret(namespace, new_secret)

def reset_kanidm_account_password(account: str) -> str:
    print(f"Resetting {account}'s password")
    resp = stream(
        client.CoreV1Api().connect_get_namespaced_pod_exec,
        'kanidm-0',
        'kanidm',
        command=["kanidmd", "recover-account", "--output", "json", account],
        stderr=False, stdin=False,
        stdout=True, tty=False
    ).splitlines()[-1]

    return json.loads(resp)['password']

# TODO Proper automation will be added later, waiting for client library update:
# https://github.com/kanidm/kanidm/pull/2301
def kanidm_login(accounts: list[str]) -> None:
    for account in accounts:
        print(f"Resetting and logging in as {account}")
        password = reset_kanidm_account_password(account)
        print(f"  password: {password}")

        # There's no way to input password using the standard library, so we have to use pexpect
        # https://stackoverflow.com/questions/2387731/use-subprocess-to-send-a-password
        print(f"  kanidm login --url https://{kanidm_host} --name {account} --ca kanidm-ca.crt")
        cli_login = pexpect.spawn(f"kanidm login --url https://{kanidm_host} --name {account} --ca kanidm-ca.crt")
        cli_login.sendline(password)
        cli_login.read()
        print(f"  Login successful for {account}")

def setup_kanidm_group(name: str) -> None:
    print(f"Creating the {name} group")
    subprocess.run(
        ["kanidm", "group", "create", "--url", f"https://{kanidm_host}", "--name", "idm_admin", "--ca", "kanidm-ca.crt", name],
        capture_output=True,
    )

def setup_kanidm_oauth_app(name: str, redirect_uri: str) -> None:
    print(f"Setting up the {name} application")
    try:
        print("  Setting up the system")
        print(f"    kanidm system oauth2 create --url https://{kanidm_host} --name idm_admin --ca kanidm-ca.crt {name} {name} {redirect_uri}")
        subprocess.run(
            ["kanidm", "system", "oauth2", "create", "--url", f"https://{kanidm_host}", "--name", "idm_admin", "--ca", "kanidm-ca.crt", name, name, redirect_uri],
            capture_output=True,
            check=True,
        )
    except subprocess.CalledProcessError as e:
        print(f"  Oops!\n${e}")
        return

    # TODO https://github.com/dexidp/dex/pull/3188
    print("  Step 2...")
    print(f"    kanidm system oauth2 warning-insecure-client-disable-pkce --url https://{kanidm_host} --name idm_admin --ca kanidm-ca.crt {name}")
    subprocess.run(
        ["kanidm", "system", "oauth2", "warning-insecure-client-disable-pkce", "--url", f"https://{kanidm_host}", "--name", "idm_admin", "--ca", "kanidm-ca.crt", name],
        capture_output=True,
        check=True,
    )

    print("  Step 3")
    print(f"    kanidm system oauth2 create-scope-map --url https://{kanidm_host} --name idm_admin --ca kanidm-ca.crt {name} editor openid profile email groups")
    subprocess.run(
        # TODO better group management
        ["kanidm", "system", "oauth2", "create-scope-map", "--url", f"https://{kanidm_host}", "--name", "idm_admin", "--ca", "kanidm-ca.crt", name, "editor", "openid", "profile", "email", "groups"],
        capture_output=True,
        check=True,
    )

    print("  Step 4")
    print(f"    kanidm system oauth2 show-basic-secret --url https://{kanidm_host} --name idm_admin --ca kanidm-ca.crt --output json {name}")
    client_secret = json.loads(subprocess.run(
        ["kanidm", "system", "oauth2", "show-basic-secret", "--url", f"https://{kanidm_host}", "--name", "idm_admin", "--ca", "kanidm-ca.crt", "--output", "json", name],
        capture_output=True,
        check=True,
    ).stdout.decode("utf-8"))['secret']

    print(" Step 5")
    apply_secret(
        f"kanidm.{name}",
        "global-secrets",
        {
            'client_id': base64.b64encode(name.encode("utf-8")).decode("utf-8"),
            'client_secret': base64.b64encode(client_secret.encode("utf-8")).decode("utf-8"),
        }
    )

def main() -> None:
    with Console().status("Completing the remaining sorcery"):
        kanidm_groups = [
            # TODO better group management
            {'name': 'editor'},
        ]

        kanidm_oauth_apps = [
            {'name': 'dex', 'redirect_uri': f"https://{client.NetworkingV1Api().read_namespaced_ingress('dex', 'dex').spec.rules[0].host}/callback"},
        ]

        get_root_ca_secret_ca("saliman-root-cert", "cert-manager")
        get_kanidm_tls_secret_ca("kanidm-tls-certificate", "kanidm")
        kanidm_login(["admin", "idm_admin"])

        for group in kanidm_groups:
            setup_kanidm_group(group['name'])

        # get_kanidm_tls_secret_ca("kanidm-tls-certificate", "kanidm")
        for app in kanidm_oauth_apps:
            setup_kanidm_oauth_app(app['name'], app['redirect_uri'])

if __name__ == '__main__':
    main()
