#!/bin/sh

set -eu

account="${1}"

echo "WARNING: Kanidm admin can do anything in the cluster, only use it for just enough initial setup or in emergencies." >&2

# If we already have a kube config, assume the homelab is in it.
if [ -f ~/.kube/config ]; then
    kubectl config use-context homelab
else
    export KUBECONFIG=./metal/kubeconfig.yaml
fi

kubectl exec -it -n kanidm statefulset/kanidm -- kanidmd recover-account "${account}"
