#!/bin/sh

username="${1}"
fullname="${2}"
mail="${3}"

# If we already have a kube config, assume the homelab is in it.
if [ -f ~/.kube/config ]; then
    kubectl config use-context homelab
else
    export KUBECONFIG=./metal/kubeconfig.yaml
fi

host="$(kubectl get ingress --namespace kanidm kanidm --output jsonpath='{.spec.rules[0].host}')"

kanidm person create "${username}" "${fullname}" --url "https://${host}" --ca kanidm-ca.crt --name idm_admin
kanidm person update "${username}" --url "https://${host}" --ca kanidm-ca.crt --name idm_admin --mail "${mail}"
# TODO better group management
kanidm group add-members "editor" "${username}" --url "https://${host}" --ca kanidm-ca.crt --name idm_admin
kanidm person credential create-reset-token "${username}" --url "https://${host}" --ca kanidm-ca.crt --name idm_admin
