#!/usr/bin/env bash

echo "Installing xorriso and mkdocs"
sudo apt install -y xorriso mkdocs

echo "Installing required 'pip' packages"
pip install rich kubernetes mkdocs material mkdocs-material

echo "Installing docker Ansible plugin"
ansible-galaxy collection install community.docker

echo "Adding firewall rules for PXE"
sudo ufw allow from 192.168.1.0/24 to any port 67 comment 'DHCP'
sudo ufw allow from 192.168.1.0/24 to any port 68 comment 'DHCP'
sudo ufw allow from 192.168.1.0/24 to any port 69 comment 'TFTP'

