elementweb:
  ingress:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      external-dns.alpha.kubernetes.io/target: "homelab-tunnel.saliman.net"
      external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
    hosts:
      - host: &frontend_host chat.saliman.net
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: element-tls-certificate
        hosts:
          - *frontend_host
  config:
    default:
      base_url: https://matrix.saliman.net
      server_name: saliman.net

dendrite:
  dendrite_config:
    global:
      server_name: matrix.saliman.net
  ingress:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hostName: matrix.saliman.net
    tls:
      - hosts:
          - matrix.saliman.net
        secretName: matrix-tls-certificate
  postgresql:
    enabled: true
