ingress-nginx:
  controller:
    admissionWebhooks:
      timeoutSeconds: 30
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
  # Allow git to access the gitea server on the ssh port.
  tcp:
    22: gitea/gitea-ssh:22
